version: "3"

services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - '5433:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    command: -p 5433

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle && rails s -p 3001 -b '0.0.0.0'"
    env_file:
      - .env
    volumes:
      - .:/app
      - node_modules_store:/app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - db

volumes:
  postgres_data:
  node_modules_store:
