default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: survey_development

test:
  <<: *default
  database: survey_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %> 

