default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: app_development
  host: db
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>

test:
  <<: *default
  database: app_test
  host: db
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %> 
