# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

# File.open("test.txt", "w") { |f| 
# x = Survey.first.questions.all.map{ |q|
# {
# type: q.type.to_s,
# position: q.position,
# answer_options: q.answer_options,
# validation_rules: q.validation_rules,
# section: q.section,
# question_text: q.question_text.to_s }}
# f.write x
# }


# File.open("test.txt", "w") { |f| 
# x = Attempt.first.answers.all.map{ |q|
# {
# answer_text: q.answer_text }}
# f.write x
# }


user = User.create email: 'test@test.com', password: '123qwe', password_confirmation: '123qwe'

client = Client.create name: 'Chedraui'

# client = Client.first
# survey = Survey.first
survey = Survey.create name: 'Ong', introduction: "<div class=\"trix-content\">\n  <div>\n<strong>Estimada ONG<br></strong><br>\n</div><div>En Grupo Chedraui nos interesa mejorar de manera continua y asegurar la adecuada ejecución de nuestras iniciativas en temas de sustentabilidad. Por ello, agradeceremos tu participación en esta encuesta y nos compartas tu opinión sobre la importancia que algunos temas tienen para ti.</div><div>\n<br>Tus respuestas son importantes para identificar tus intereses y de qué manera te sientes impactado por alguno de estos temas, cómo podemos mejorar los impactos negativos, y los positivos y fortalecer nuestra comunicación.</div>\n</div>\n",
                       conclusion: "<div class=\"trix-content\">\n  <div><strong>Hemos finalizado la encuesta. ¡Muchas gracias por tu participación!</strong></div>\n</div>\n",
                       client: client

attempt = survey.attempts.create completed:true

[
  { type: 'Questions::Radio',
   position: 1,
   answer_options: "Sí\r\nNo",
   validation_rules: { 'presence' => '1',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 1,
   question_text: "<div class=\"trix-content\">\n  <div>¿Consideras que Grupo Chedraui impacta positiva o negativamente a tu organización al adoptar programas o acciones que se relacionen con los temas ambientales,
sociales y de gobierno corporativo?</div><div><br></div>\n</div>\n" },
 { type: 'Questions::Short',
   position: 2,
   answer_options: '',
   validation_rules: { 'presence' => '1',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 1,
   question_text: "<div class=\"trix-content\">\n  <div>¿Porqué?</div>\n</div>\n" },
 { type: 'Questions::Information',
   position: 3,
   answer_options: '',
   validation_rules: { 'presence' => '0',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 2,
   question_text: "<div class=\"trix-content\">\n  <div>Grupo Chedraui identifica su contribución a la sustentabilidad a través del cumplimiento de su responsabilidad en 4 vertientes –operativa y financiera,
social,
ambiental y de gobernanza– y cuyos avances son reportados en su Informe Anual y de Sustentabilidad. ¿Cuál de los 4 aspectos consideras que debe ser robustecido y en qué plazo?<br><br>\n</div><div><br></div>\n</div>\n" },
 { type: 'Questions::MatrixHeader',
   position: 4,
   answer_options: "Corto plazo (en el próximo año)\r\nMediano plazo (en los próximos 2-3 años)\r\nLargo plazo (5 años en adelante)",
   validation_rules: { 'presence' => '0',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 2,
   question_text: "<div class=\"trix-content\">\n  <div><strong>Aspecto</strong></div>\n</div>\n" },
 { type: 'Questions::MatrixRadio',
   position: 5,
   answer_options: "1\r\n2\r\n3",
   validation_rules: { 'presence' => '1',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 2,
   question_text: "<div class=\"trix-content\">\n  <div>Desempeño operativo y financiero</div>\n</div>\n" },
 { type: 'Questions::MatrixRadio',
   position: 6,
   answer_options: "1\r\n2\r\n3",
   validation_rules: { 'presence' => '1',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 2,
   question_text: "<div class=\"trix-content\">\n  <div>Responsabilidad social</div>\n</div>\n" },
 { type: 'Questions::MatrixRadio',
   position: 7,
   answer_options: "1\r\n2\r\n3",
   validation_rules: { 'presence' => '0',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 2,
   question_text: "<div class=\"trix-content\">\n  <div>Responsabilidad ambiental</div>\n</div>\n" },
 { type: 'Questions::MatrixRadio',
   position: 8,
   answer_options: "1\r\n2\r\n3",
   validation_rules: { 'presence' => '1',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 2,
   question_text: "<div class=\"trix-content\">\n  <div>Gobierno corporativo</div>\n</div>\n" },
 { type: 'Questions::Information',
   position: 9,
   answer_options: '',
   validation_rules: { 'presence' => '0',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 3,
   question_text: "<div class=\"trix-content\">\n  <div>Del 1 al 10,
¿qué tan satisfecho te encuentras con la información proporcionada por Grupo Chedraui sobre los riesgos,
oportunidades y avances en materia económica,
ambiental,
social y de gobernanza (ASG)?</div><div><br></div>\n</div>\n" },
 { type: 'Questions::MatrixHeader',
   position: 10,
   answer_options: "Poco satisfecho\r\nMedianamente satisfecho\r\nMuy satisfecho",
   validation_rules: { 'presence' => '0',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 3,
   question_text: "<div class=\"trix-content\">\n  <div><strong>Atributos de la información ASG</strong></div>\n</div>\n" },
 { type: 'Questions::MatrixRating',
   position: 11,
   answer_options: "1\r\n2\r\n3\r\n4\r\n5\r\n6\r\n7\r\n8\r\n9\r\n10",
   validation_rules: { 'presence' => '1',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 3,
   question_text: "<div class=\"trix-content\">\n  <div>Calidad</div>\n</div>\n" },
 { type: 'Questions::MatrixRating',
   position: 12,
   answer_options: "1\r\n2\r\n3\r\n4\r\n5\r\n6\r\n7\r\n8\r\n9\r\n10",
   validation_rules: { 'presence' => '1',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 3,
   question_text: "<div class=\"trix-content\">\n  <div>Suficiencia</div>\n</div>\n" },
 { type: 'Questions::MatrixRating',
   position: 13,
   answer_options: "1\r\n2\r\n3\r\n4\r\n5\r\n6\r\n7\r\n8\r\n9\r\n10",
   validation_rules: { 'presence' => '1',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 3,
   question_text: "<div class=\"trix-content\">\n  <div>Disponibilidad</div>\n</div>\n" },
 { type: 'Questions::MatrixRating',
   position: 14,
   answer_options: "1\r\n2\r\n3\r\n4\r\n5\r\n6\r\n7\r\n8\r\n9\r\n10",
   validation_rules: { 'presence' => '1',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 3,
   question_text: "<div class=\"trix-content\">\n  <div>Pertinencia</div>\n</div>\n" },
 { type: 'Questions::MatrixRating',
   position: 15,
   answer_options: "1\r\n2\r\n3\r\n4\r\n5\r\n6\r\n7\r\n8\r\n9\r\n10",
   validation_rules: { 'presence' => '1',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 3,
   question_text: "<div class=\"trix-content\">\n  <div>Frecuencia</div>\n</div>\n" },
 { type: 'Questions::Checkbox',
   position: 16,
   answer_options: "Es una tendencia\r\nEs lo correcto\r\nPara ayudar a los inversionistas a realizar una inversión informada y responsable\r\nPara mitigar riesgos de inversión\r\nPara mitigar riesgos reputacionales\r\nPara mitigar riesgos regulatorios que consideran temas ASG\r\nPara cumplir con las disposiciones del Consejo de Administración\r\nPara cumplir con requerimientos por parte de los clientes\r\nPara cumplir con solicitudes de los colaboradores\r\nPara mantener un nivel promedio respecto al sector o competencia",
   validation_rules: { 'presence' => '1',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 4,
   question_text: "<div class=\"trix-content\">\n  <div>De la siguiente lista,
elige los tres principales factores por los que consideras que Grupo Chedraui debe robustecer la gestión de temas ambientales,
sociales y de gobernanza (ASG),
así como comunicar los riesgos,
oportunidades y avances en esta materia.</div>\n</div>\n" },
 { type: 'Questions::Information',
   position: 17,
   answer_options: '',
   validation_rules: { 'presence' => '0',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 5,
   question_text: "<div class=\"trix-content\">\n  <div>Del 1 al 10,
¿qué tan satisfecho te encuentras con la información proporcionada por Grupo Chedraui acerca de las iniciativas que lleva a cabo Fundación Chedraui?</div>\n</div>\n" },
 { type: 'Questions::MatrixHeader',
   position: 18,
   answer_options: "Poco satisfecho\r\nMedianamente satisfecho\r\nMuy satisfecho",
   validation_rules: { 'presence' => '0',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 5,
   question_text: "<div class=\"trix-content\">\n  <div><strong>Atributos de la información ASG</strong></div>\n</div>\n" },
 { type: 'Questions::MatrixRating',
   position: 19,
   answer_options: "1\r\n2\r\n3\r\n4\r\n5\r\n6\r\n7\r\n8\r\n9\r\n10",
   validation_rules: { 'presence' => '1',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 5,
   question_text: "<div class=\"trix-content\">\n  <div>Calidad</div>\n</div>\n" },
 { type: 'Questions::MatrixRating',
   position: 20,
   answer_options: "1\r\n2\r\n3\r\n4\r\n5\r\n6\r\n7\r\n8\r\n9\r\n10",
   validation_rules: { 'presence' => '1',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 5,
   question_text: "<div class=\"trix-content\">\n  <div>Suficiencia</div>\n</div>\n" },
 { type: 'Questions::MatrixRating',
   position: 21,
   answer_options: "1\r\n2\r\n3\r\n4\r\n5\r\n6\r\n7\r\n8\r\n9\r\n10",
   validation_rules: { 'presence' => '1',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 5,
   question_text: "<div class=\"trix-content\">\n  <div>Disponibilidad</div>\n</div>\n" },
 { type: 'Questions::MatrixRating',
   position: 22,
   answer_options: "1\r\n2\r\n3\r\n4\r\n5\r\n6\r\n7\r\n8\r\n9\r\n10",
   validation_rules: { 'presence' => '1',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 5,
   question_text: "<div class=\"trix-content\">\n  <div>Pertinencia</div>\n</div>\n" },
 { type: 'Questions::MatrixRating',
   position: 23,
   answer_options: "1\r\n2\r\n3\r\n4\r\n5\r\n6\r\n7\r\n8\r\n9\r\n10",
   validation_rules: { 'presence' => '1',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 5,
   question_text: "<div class=\"trix-content\">\n  <div>Frecuencia</div>\n</div>\n" },
 { type: 'Questions::Information',
   position: 24,
   answer_options: '',
   validation_rules: { 'presence' => '0',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 6,
   question_text: "<div class=\"trix-content\">\n  <div>Proporciona un valor en la escala del 1 al 10 (siendo el <strong>1</strong> el <strong>menor impacto</strong> y <strong>10 </strong>el de mayor impacto) dependiendo de la relevancia que tienen para ti las iniciativas que Grupo Chedraui lleva a cabo a través de Fundación Chedraui.</div>\n</div>\n" },
 { type: 'Questions::Information',
   position: 25,
   answer_options: '',
   validation_rules: { 'presence' => '0',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 6,
   question_text: "<div class=\"trix-content\">\n  <div><strong>Educación</strong></div>\n</div>\n" },
 { type: 'Questions::Select',
   position: 26,
   answer_options: "1\r\n2\r\n3\r\n4\r\n5\r\n6\r\n7\r\n8\r\n9\r\n10",
   validation_rules: { 'presence' => '1',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 6,
   question_text: "<div class=\"trix-content\">\n  <div>Educación a las escuelas Liceos de Artes y Oficios,
A.C.</div>\n</div>\n" },
 { type: 'Questions::Select',
   position: 27,
   answer_options: "1\r\n2\r\n3\r\n4\r\n5\r\n6\r\n7\r\n8\r\n9\r\n10",
   validation_rules: { 'presence' => '1',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 6,
   question_text: "<div class=\"trix-content\">\n  <div>Llevar a cabo educación en línea</div>\n</div>\n" },
 { type: 'Questions::Select',
   position: 28,
   answer_options: "1\r\n2\r\n3\r\n4\r\n5\r\n6\r\n7\r\n8\r\n9\r\n10",
   validation_rules: { 'presence' => '1',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 6,
   question_text: "<div class=\"trix-content\">\n  <div>Programa de Becas para educación media y superior</div>\n</div>\n" },
 { type: 'Questions::Information',
   position: 29,
   answer_options: '',
   validation_rules: { 'presence' => '0',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 6,
   question_text: "<div class=\"trix-content\">\n  <div><strong>Salud</strong></div>\n</div>\n" },
 { type: 'Questions::Select',
   position: 30,
   answer_options: "1\r\n2\r\n3\r\n4\r\n5\r\n6\r\n7\r\n8\r\n9\r\n10",
   validation_rules: { 'presence' => '1',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 6,
   question_text: "<div class=\"trix-content\">\n  <div>Apoyo a más instituciones de salud que brindan asistencia médica a personas que no tengan capacidad económica</div>\n</div>\n" },
 { type: 'Questions::Select',
   position: 31,
   answer_options: "1\r\n2\r\n3\r\n4\r\n5\r\n6\r\n7\r\n8\r\n9\r\n10",
   validation_rules: { 'presence' => '1',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 6,
   question_text: "<div class=\"trix-content\">\n  <div>Donación de equipo médico a hospitales</div>\n</div>\n" },
 { type: 'Questions::Information',
   position: 32,
   answer_options: '',
   validation_rules: { 'presence' => '0',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 6,
   question_text: "<div class=\"trix-content\">\n  <div><strong>Alimentación</strong></div>\n</div>\n" },
 { type: 'Questions::Select',
   position: 33,
   answer_options: "1\r\n2\r\n3\r\n4\r\n5\r\n6\r\n7\r\n8\r\n9\r\n10",
   validation_rules: { 'presence' => '1',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 6,
   question_text: "<div class=\"trix-content\">\n  <div>Entrega de alimentos a ONGs y Bancos de Alimentos</div>\n</div>\n" },
 { type: 'Questions::Select',
   position: 34,
   answer_options: "1\r\n2\r\n3\r\n4\r\n5\r\n6\r\n7\r\n8\r\n9\r\n10",
   validation_rules: { 'presence' => '1',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 6,
   question_text: "<div class=\"trix-content\">\n  <div>Donaciones en especie de productos</div>\n</div>\n" },
 { type: 'Questions::Information',
   position: 35,
   answer_options: '',
   validation_rules: { 'presence' => '0',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 6,
   question_text: "<div class=\"trix-content\">\n  <div><strong>Asistencia Social</strong></div>\n</div>\n" },
 { type: 'Questions::Select',
   position: 36,
   answer_options: "1\r\n2\r\n3\r\n4\r\n5\r\n6\r\n7\r\n8\r\n9\r\n10",
   validation_rules: { 'presence' => '1',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 6,
   question_text: "<div class=\"trix-content\">\n  <div>Apoyo a personas de la tercera edad</div>\n</div>\n" },
 { type: 'Questions::Select',
   position: 37,
   answer_options: "1\r\n2\r\n3\r\n4\r\n5\r\n6\r\n7\r\n8\r\n9\r\n10",
   validation_rules: { 'presence' => '1',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 6,
   question_text: "<div class=\"trix-content\">\n  <div>Mejoramiento urbano</div>\n</div>\n" },
 { type: 'Questions::Select',
   position: 38,
   answer_options: "1\r\n2\r\n3\r\n4\r\n5\r\n6\r\n7\r\n8\r\n9\r\n10",
   validation_rules: { 'presence' => '1',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 6,
   question_text: "<div class=\"trix-content\">\n  <div>Donaciones monetarias para diversas causas</div>\n</div>\n" },
 { type: 'Questions::Radio',
   position: 39,
   answer_options: "Sí lo conozco y lo he leído\r\nSí lo conozco, pero no lo he leído\r\nNo lo conozco, pero me gustaría saber más\r\nNo lo conozco",
   validation_rules: { 'presence' => '1',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 7,
   question_text: "<div class=\"trix-content\">\n  <div>¿Conoces el Informe Anual y de Sustentabilidad de Grupo Chedraui? </div>\n</div>\n" },
 { type: 'Questions::Checkbox',
   position: 40,
   answer_options: "Comunicado\r\nMedios electrónicos\r\nCorreo\r\nOtro",
   validation_rules: { 'presence' => '0',
                       'presence_on_question' => '39',
                       'presence_on_answers' => "Sí lo conozco y lo he leído\r\nSí lo conozco, pero no lo he leído",
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 7,
   question_text: "<div class=\"trix-content\">\n  <div> En caso de que sí lo conozcas,
¿cómo te enteraste de él?</div>\n</div>\n" },
 { type: 'Questions::Short',
   position: 41,
   answer_options: '',
   validation_rules: { 'presence' => '0',
                       'presence_on_question' => '40',
                       'presence_on_answers' => 'Otro',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 7,
   question_text: "<div class=\"trix-content\">\n  <div>Por favor,
especifica:</div>\n</div>\n" },
 { type: 'Questions::Information',
   position: 42,
   answer_options: '',
   validation_rules: { 'presence' => '0',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 8,
   question_text: "<div class=\"trix-content\">\n  <div>Por favor,
evalúa cada tema de las dimensiones económica,
ambiental,
social y de gobierno corporativo presentado a continuación.</div><div>\n<br>Proporciona un valor en la escala del 1 al 10,
(siendo el <strong>1</strong> el <strong>menor impacto</strong> y <strong>10 </strong>el de mayor impacto<strong>)</strong> dependiendo de la relevancia que tiene para ti que Grupo Chedraui establezca acciones <strong>sobre el tema Económico</strong> (los valores pueden repetirse).</div><div>\n<br>Que <strong>Grupo Chedraui </strong>establezca acciones como…</div>\n</div>\n" },
 { type: 'Questions::Select',
   position: 43,
   answer_options: "1\r\n2\r\n\r\n3\r\n4\r\n5\r\n6\r\n7\r\n8\r\n9\r\n10",
   validation_rules: { 'presence' => '1',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 8,
   question_text: "<div class=\"trix-content\">\n  <div>Tener publicidad que cumpla con todas las leyes,
no discrimine o contenga mensajes confusos.</div>\n</div>\n" },
 { type: 'Questions::Select',
   position: 44,
   answer_options: "1\r\n2\r\n3\r\n4\r\n5\r\n6\r\n7\r\n8\r\n9\r\n10",
   validation_rules: { 'presence' => '1',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 8,
   question_text: "<div class=\"trix-content\">\n  <div>Comunicar cada año sus ingresos,
cuánto paga de impuestos,
cuánto paga a sus proveedores,
cuánto gasta en salarios y beneficios y cuánto invierte en innovación y tecnología,
mejoras ambientales y en las comunidades.</div>\n</div>\n" },
 { type: 'Questions::Select',
   position: 45,
   answer_options: "1\r\n2\r\n3\r\n4\r\n5\r\n6\r\n7\r\n8\r\n9\r\n10",
   validation_rules: { 'presence' => '1',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 8,
   question_text: "<div class=\"trix-content\">\n  <div>Comunicar información sobre los estados en los que tiene presencia y los tipos de producto con los que cuenta,
así como los impactos de sus operaciones.</div>\n</div>\n" },
 { type: 'Questions::Select',
   position: 46,
   answer_options: "1\r\n2\r\n3\r\n4\r\n5\r\n6\r\n7\r\n8\r\n9\r\n10",
   validation_rules: { 'presence' => '1',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 8,
   question_text: "<div class=\"trix-content\">\n  <div>Establecer indicadores para medir la calidad,
competitividad,
productividad,
innovación y eficiencia de sus operaciones,
e identificar las mejoras a realizar.</div>\n</div>\n" },
 { type: 'Questions::Select',
   position: 47,
   answer_options: "1\r\n2\r\n3\r\n4\r\n5\r\n6\r\n7\r\n8\r\n9\r\n10",
   validation_rules: { 'presence' => '1',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 8,
   question_text: "<div class=\"trix-content\">\n  <div>Garantizar que la información que se proporciona a los clientes en los contratos sea clara y que cada vez más se mejoren los productos que se ofrecen a los clientes.</div>\n</div>\n" },
 { type: 'Questions::Select',
   position: 48,
   answer_options: "1\r\n2\r\n3\r\n4\r\n5\r\n6\r\n7\r\n8\r\n9\r\n10",
   validation_rules: { 'presence' => '1',
                       'presence_on_question' => '',
                       'presence_on_answers' => '',
                       'uniqueness_on_section' => '',
                       'minimum' => '',
                       'maximum' => '',
                       'greater_than_or_equal_to' => '',
                       'less_than_or_equal_to' => '' },
   section: 8,
   question_text: "<div class=\"trix-content\">\n  <div>Realizar encuestas para conocer la satisfacción del cliente,
que cuente con buzón o teléfonos para recibir y atender quejas por parte del cliente y cumplir con las leyes de protección de datos personales.</div>\n</div>\n" }
].each do |question_attributes|
    question = Question.create(
      survey: survey,
      type: question_attributes[:type],
      position: question_attributes[:position],
      answer_options: question_attributes[:answer_options],
      validation_rules: question_attributes[:validation_rules],
      section: question_attributes[:section],
      question_text: question_attributes[:question_text]
    )
  end

[
  { answer_text: 'Sí' },
  { answer_text: 'awse' },
  { answer_text: nil },
  { answer_text: nil },
  { answer_text: '3' },
  { answer_text: '2' },
  { answer_text: '3' },
  { answer_text: '3' },
  { answer_text: nil },
  { answer_text: nil },
  { answer_text: '10' },
  { answer_text: '9' },
  { answer_text: '10' },
  { answer_text: '10' },
  { answer_text: '8' },
  { answer_text: "Para ayudar a los inversionistas a realizar una inversión informada y responsable\r\nPara cumplir con las disposiciones del Consejo de Administración" },
  { answer_text: nil },
  { answer_text: nil },
  { answer_text: '10' },
  { answer_text: '9' },
  { answer_text: '8' },
  { answer_text: '9' },
  { answer_text: '10' },
  { answer_text: nil },
  { answer_text: nil },
  { answer_text: '9' },
  { answer_text: '8' },
  { answer_text: '9' },
  { answer_text: nil },
  { answer_text: '8' },
  { answer_text: '7' },
  { answer_text: nil },
  { answer_text: '8' },
  { answer_text: '9' },
  { answer_text: nil },
  { answer_text: '5' },
  { answer_text: '8' },
  { answer_text: '9' },
  { answer_text: 'Sí lo conozco, pero no lo he leído' },
  { answer_text: "Comunicado\r\nOtro" },
  { answer_text: 'asdas' },
  { answer_text: nil },
  { answer_text: '9' },
  { answer_text: '8' },
  { answer_text: '5' },
  { answer_text: '8' },
  { answer_text: '9' },
  { answer_text: '8' }
].each_with_index do |answer_attributes, index|
    answer = Answer.create(
      question: survey.questions.find_by(position: index + 1),
      attempt: attempt,
      answer_text: answer_attributes[:answer_text],
    )
  end







